//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8BB1_Register_Enums.h>
#include <stdint.h>
#include <state_machine.h>

//-----------------------------------------------------------------------------
// UART0_ISR
//-----------------------------------------------------------------------------
//
// UART0 ISR Content goes here. Remember to clear flag bits:
// SCON0::RI (Receive Interrupt Flag)
// SCON0::TI (Transmit Interrupt Flag)
//
//-----------------------------------------------------------------------------

SI_INTERRUPT (UART0_ISR, UART0_IRQn)
{

	if (SCON0 & SCON0_RI__SET) {
		uint8_t rx = SBUF0;
		SCON0 &= ~SCON0_RI__SET;
		state_machine_handle_rx_byte(rx);
	}
	if (SCON0 & SCON0_TI__SET) {
		SCON0 &= ~SCON0_TI__SET;
		state_machine_handle_tx_ready();
	}
}

//-----------------------------------------------------------------------------
// ADC0EOC_ISR
//-----------------------------------------------------------------------------
//
// ADC0EOC ISR Content goes here. Remember to clear flag bits:
// ADC0CN0::ADINT (Conversion Complete Interrupt Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (ADC0EOC_ISR, ADC0EOC_IRQn)
{

}

